dependencies:
- name: cartservices
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: evntxzcp
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: evntxzweb
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.10
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: locationservices
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: productservices
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: purchaseservices
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: userservices
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
